dask/dask-image

.gitignore

Have `git` ignore `.pytest_cache/`.

Ignore `.pytest_cache/`

---

HISTORY.rst

Fixes https://github.com/dask/dask-image/issues/34
Basically point out that this is the first release and that includes some basic functionality for work with Dask Arrays containing image data.

Document additions to 0.1.0

---

dask_image/ndmeasure/_utils.py

Instead of using the Python `sum` function on Dask Arrays, which will handle the reduction one pair at a time thus generating a large graph, use `atop` with a special summation kernel. This handles summation of all of the Dask Arrays in one function and returns the result. Thus simplifying the addition into one node. To simplify the Dask graph further, move the creation of singleton axes into the `_ravel_shape_indices` kernel function as well. This avoids adding these steps needlessly to the graph of each `arange`. Plus NumPy should be able to do these for basically free. As a result graph construction by `_ravel_shape_indices` should be merely using `arange` to construct indices for each dimensions and combining these into the resultant raveled indices with `atop` and the custom kernel …

Consolidate summation in `_ravel_shape_indices`

---

tests/test_dask_image/test_ndmeasure/test_core.py

Some minor cleanup of `test_labeled_comprehension_struct`.

Cleanup `test_labeled_comprehension_struct`

---

CONTRIBUTING.rst

Add instructions for building docs with sphinx to CONTRIBUTING.rst

Add instructions for building docs with sphinx to CONTRIBUTING.rst

---

.appveyor.yml
.appveyor_support/environments/tst_py27.yml
.appveyor_support/environments/tst_py35.yml
.appveyor_support/environments/tst_py36.yml
.appveyor_support/environments/tst_py37.yml
.circleci/config.yml
.circleci/environments/tst_py27.yml
.circleci/environments/tst_py35.yml
.circleci/environments/tst_py36.yml
.circleci/environments/tst_py37.yml
.travis.yml
.travis_support/environments/tst_py27.yml
.travis_support/environments/tst_py35.yml
.travis_support/environments/tst_py36.yml
.travis_support/environments/tst_py37.yml

Add Python 3.7 to Travis CI

---

.github/PULL_REQUEST_TEMPLATE.md
setup.py

Update the repo to list Python 3.7 support alongside other Python versions that are supported.

Note Python 3.7 support

---

tests/test_dask_image/test_ndfourier/test__utils.py

Provide integral data to `_norm_args` to test that it does cast this to float.

Test float cast in `_norm_args`

---

HISTORY.rst

Add the release notes for upcoming dask-image release 0.3.0

Update HISTORY.rst with 0.3.0 release notes

---

HISTORY.rst

Fix another typo in HISTORY.rst

---

docs/release/generate_release_notes.py
docs/release/release_guide.rst

This PR includes:
1. A script to generate draft release notes, and
2. A step-by-step guide to the release procedure

Developer documentation: release guide

---

HISTORY.rst

Update HISTORY.rst with release notes for 0.4.0

---

AUTHORS.rst

Before you submit a pull request, check that it meets these guidelines:
1. The pull request should include tests.
2. If the pull request adds functionality, the docs should be updated. Put
your new functionality into a function with a docstring, and add the
feature to the list in README.rst.
3. The pull request should work for Python 3.6, 3.7, and 3.8. Check
https://travis-ci.org/dask/dask-image/pull_requests
and make sure that the tests pass for all supported Python versions.

DOCS: Update information in AUTHORS.rst

---

docs/quickstart.rst

This is a sprint contribution in ScipyJapan2020 (#163) and additional contents of #169 .

DOCUMENTATION: Add link to SciPy Japan 2020 talk

---

dask_image/imread/__init__.py
tests/test_dask_image/test_imread/test_core.py

FEATURE: pathlib input for imread functions #139 .
This is a sprint contribution in ScipyJapan2020 (#163) .

FEATURE: pathlib input for imread functions #139

---

HISTORY.rst
docs/release/release_guide.rst

Release notes for the 0.5.0 release of dask-image

V0.5.0 release

---

HISTORY.rst

Add release notes for v0.6.0

---

HISTORY.rst

Release notes updated for v0.6.0

Release notes updated for v0.6.0

---

HISTORY.rst

Release notes, add line for bugfix PR #205

Release notes, add line for bugfix PR #205

---

HISTORY.rst

Update the release date for v0.6.0 in HISTORY.rst

Update HISTORY.rst, fix date for release v0.6.0

---

HISTORY.rst
docs/release/release_guide.rst

Release notes for v2022.09.0
Release requested by Matt McCormick here: https://github.com/dask/dask-image/issues/269

Release notes for v2022.09.0

---

HISTORY.rst

Short description of the patch release.

Added 2023.08.1 patch release notes to HISTORY.rst
