dask/dask-image

- environment_doc.yml
Closes https://github.com/dask/dask-image/issues/2 (hopefully 🍀)
Appears we were using `Sphinx` instead of `sphinx` in the `environment_doc.yml` file. Not sure if this was causing problems with RTD, but it does seem like the right place to start.
> Fix casing of `sphinx` in doc environment file

- docs/conf.py
Fixes https://github.com/dask/dask-image/issues/2
As of 1.7.0+, the first argument to `sphinx.apidoc.main` need not be the executable. So this checks the version of `sphinx` in use to make sure the executable path is only included on older versions of Sphinx.
> Fix sphinx 1.7 on RTD

- docs/conf.py
- rtd_requirements.txt
In Sphinx 1.7, it appears that `apidoc` was moved from `sphinx` to `sphinx.ext`. This adopts an `ImportError` based workaround to handle both cases. Also reverts a previous attempt to solve this issue, which did not end up working.
xref: https://github.com/sphinx-doc/sphinx/issues/5104
> Handle Sphinx changes related to `apidoc` location

- docs/conf.py
- rtd_requirements.txt
Accidentally snuck in with PR ( https://github.com/dask/dask-image/pull/5 ). Though it is actually unused. So drop `rtd_requirements.txt`.
> Drop unneeded rtd_requirements.txt

- .github/PULL_REQUEST_TEMPLATE.md
- setup.py
Already Python 3.4 is not planned for support here and is not being tested against. This removes the last few lingering references to Python 3.4.
> Cleanup Python 3.4 remnants

- docs/conf.py
- environment_doc.yml
Switch from the Sphinx default stylesheet to Dask's standard stylesheet. Should make this fit in better with the other `dask-*` projects.
xref: https://github.com/dask/dask-image/issues/33#issuecomment-417490798
> Use Dask's standard doc stylesheet

- setup.py
It seems that SciPy 1.0.0+ causes some tests to fail. So go ahead and require SciPy to be pre-1.0.0 to ensure things don't break accidentally. Will need to revisit the cause of the failures separately and address them.
> Require SciPy pre-1.0.0

- README.rst
- docs/index.rst
- docs/readme.rst
Partially addresses https://github.com/dask/dask-image/issues/38
Moves the README content into the index page and drops the README from the docs.
> Consolidate README content in docs

- README.rst
Just to clarify that the Conda package is in conda-forge, use the conda-forge badge from Shields.io in the README.
> Use conda-forge badge

- dask_image/ndfourier/__init__.py
In all cases `sigma` is squared, the result is divided by `2`, and the negative of the result taken. These can be factored out into a common change to just `sigma` that is reused in all of the other computations. Admittedly Dask is smart enough to capture the reused computation of `sigma` squared, but it is not a symbolic algebra library. So it won't be able to pick up on the other changes, but we can. This should simplify the resulting graph and make it easy to reuse some common changes to `sigma` before `tensordot` is computed over multiple arrays and these changes applied.
> Breakout common changes in fourier_gaussian

- dask_image/ndfourier/_utils.py
Just to ensure this scalar multiplication occurs before graph construction and is not added as operations in graph construction, enforce the order of operations by treating `2 * pi` as a quantity itself. This way we can be sure it is already computed before graph construction begins and the scalar is merely inserted into the graph as a single node.
> Perform `2 * pi` first in `_get_ang_freq_grid`

- dask_image/imread/__init__.py
- dask_image/imread/_pycompat.py
- tests/test_dask_image/test_imread/test__pycompat.py
Does some light refactoring of Python 2/3 compatibility content from `imread`.
> Refactor Python 2/3 compatibility from imread

- dask_image/_pycompat.py
- dask_image/ndfilters/_utils.py
- dask_image/ndfourier/_utils.py
- dask_image/ndmorph/_ops.py
- dask_image/ndmorph/_utils.py
- tests/test_dask_image/test__pycompat.py
Refactors out some other buried Python 2/3 compatibility code and makes better use of the shared Python 2/3 compatibility module.
> Use shared Python 2/3 compatibility module

- dask_image/ndfourier/_utils.py
This code looked a little weird and was bit packed together. Break it apart into steps so it is easier to see what is happening in `_get_freq_grid` to construct each `freq_grid_i` for each dimension.
> Cleanup freq_grid_i construction in _get_freq_grid

- dask_image/ndmorph/_utils.py
The individual packages `dask-ndfilter` and `dask-ndmorph` vendored identical versions of some utility functions. While that made sense when they were separate packages, that no longer makes since as they have been merged into `dask-image`. To simplify things a bit, simply reuse the utility functions needed from `dask-ndfilter` in `dask-ndmorph`. Should cutdown on some duplicated code and lighten maintenance burden a bit.
> Reuse `ndfilter` utility function in `ndmorph`

- dask_image/imread/__init__.py
- dask_image/imread/_utils.py
Breaks out some functionality from `imread` into a utility module. In particular pulls out the closure `_read_frame`. As `_read_frame` doesn't really need to be a closure and it's a bit cheaper to pickle and serialize module level functions, go ahead and convert `_read_frame` into a utility function that `imread` uses. Makes the code a bit cleaner as well.
> Refactor utility module for imread

- dask_image/ndmeasure/_utils.py
Make sure that NumPy's `prod` returns results that match the `dtype` of the `arange`. This is important as `prod` by default matches `float` if no other type is specified (e.g. it is given an empty sequence). While the `float` value will be handled correctly by NumPy, it's better to be explicit about the type `prod` should provide. That way if NumPy changes its behavior, we don't run into issues here.
> Force dtype of `prod` in `_ravel_shape_indices`

- dask_image/ndfourier/__init__.py
Instead of negating the result of `(sigma ** 2) / 2`, which may be a Dask Array meaning this would add more nodes to the graph, simply divide by `-2` instead. This ensures the sign still changes as intended, but this is included as part of the division step. Thus this avoids potentially adding more nodes to the Dask graph (assuming `sigma` is not concrete).
> Divide `sigma` by `-2`

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
- tests/test_dask_image/test_ndmeasure/test__utils.py
Adds a utility function `_unravel_index` to emulate NumPy's [`unravel_index`]( https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.unravel_index.html#numpy.unravel_index ) except for Dask Arrays. They are not 1-to-1 as we return a single Dask Array instead of `tuple`s of Dask Arrays. This change ends up being better suited for our use case. Include some tests for `_unravel_index`, which compare it NumPy's `unravel_index` with our modifications.
Rewrites `maximum_position` and `minimum_position` to use our `_unravel_index` function instead of rolling their own with Dask Arrays. This should create simpler, cleaner graphs for the Dask Arrays returned from `maximum_position` and `minimum_position`. Also should be easier for Dask to fuse tasks should it choose to (though we have …
> Refactor out `_unravel_index` function

- docs/conf.py
- environment_doc.yml
Switch over to Dask's new `dask-sphinx-theme` for handling documentation layout and styling. Should make it easier to keep the documentation style inline with other Dask projects.
> Use dask-sphinx-theme

- dask_image/ndmeasure/_utils.py
These lines fit within the line limit in unwrapped form. So go ahead and unwrap them.
> Unwrap some lines

- dask_image/ndmeasure/_utils.py
Pulled from PR ( https://github.com/dask/dask-image/pull/61 ).
Handle cases where there are multiple labels selected with some structure to them.
> Fixes for `_unravel_index`

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
- tests/test_dask_image/test_ndmeasure/test_core.py
Update our `labeled_comprehension` implementation so that it can handle a structured array-based scalar value. This is useful for functions that need to return a few related values from each computation (e.g. a specific value and its position). Also useful for optimizing `extrema` using a specialized kernel function, which returns multiple values from each block.
> Handle structured dtype in labeled_comprehension

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
Rewrites `extrema` to use its own custom kernel instead of relying on other functions to compute parts of the result.
> Use custom kernel for extrema

- dask_image/ndmeasure/__init__.py
Create an `empty` 1-D scalar array of the expected return type of the user function. Then store this `default` value into the 1-D scalar array. This has the advantage of raising a `ValueError` if the `default` value cannot be coerced into a scalar of the appropriate type and stored into this array. It also handles some situations better like having a 1-D scalar array provided as the `default` value by ensuring the result remains 1-D.
> Ensure `labeled_comprehension`'s `default` is 1D

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
To simplify the `histogram` implementation a bit, rewrite it using `labeled_comprehension`. Make use of `functools.partial` to bind arguments to `histogram` so that it can be used with `labeled_comprehension`. Also simplify the internal `_histogram` function into a basic kernel function following these changes. Set the return type of `labeled_comprehension` as `object` to match that of what `histogram` used prior.
> Rewrite `histogram` to use `labeled_comprehension`

- tests/test_dask_image/test_ndmeasure/test_core.py
Includes a test using `labeled_comprehension` with functions that return `object` type results. While this is also being used by `histogram` currently, it makes sense to have a test of `labeled_comprehension` for this case as well in the event that `histogram`'s implementation changes. The ability to return `object` type results is very handy for using a variety of functions with `labeled_comprehension`. So it is good to be sure that `labeled_comprehension` retains the behavior regardless of other changes.
> Test labeled_comprehension with object type

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
Makes some adjust to `extrema`'s internal structured type handling. Namely orders the fields to match the result's order. Also makes use of `OrderedDict`s to ensure that this ordering of fields is used both in the `dtype`'s construction and later steps used to split apart the different results after `extrema`'s kernel has been run by the `labeled_comprehension` call. Additionally binds the `dtype` to the `extrema` kernel function before calling it to drop code reconstructing the `dtype` within the kernel. Simplifies the surrounding code a bit.
> Adjust `extrema`'s internal structured type handling

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
Adds a custom kernel for `center_of_mass` to use with `labeled_comprehension` and rewrites `center_of_mass` using that kernel. Using a little trickier to handle the fact that `center_of_mass` returns a 1-D array instead of a scalar by packing this into a structured array instead. Names the structured array fields using `bytes` containing each index. Pulls this result apart and repacks it in the expected form before returning it to the user.
This rewrite of `center_of_mass` significantly simplifies the Dask graph, notably improves performance, and cleans up the code a bit. All of this thanks to the custom kernel used by `center_of_mass`, which now handles all computations related to the center of mass for each ROI using only the data needed and avoiding computations on data that would be …
> Rewrite `center_of_mass` using `labeled_comprehension`

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
- tests/test_dask_image/test_ndmeasure/test__utils.py
Rewrites position-based kernels to leverage 1-D structured array fields to return unraveled coordinate values. This simplifies the Dask graphs of these functions by dropping steps that performed the unraveling or repacking of these results. Should aid performance by handling more computations within a single kernel where it is easily solved as well as avoiding stacking arrays. Drops the `_unravel_index` utility function and its tests as a consequence of this change since it is no longer needed.
> Use 1-D structured array fields for position-based kernels in `ndmeasure`

- dask_image/ndmeasure/__init__.py
To simplify iterations over labels and consolidation of the results in `labeled_comprehension`, make use of NumPy's `ndindex` instead of rolling our own. Makes the code a bit easier to follow and is a bit faster than our hand rolled implementation.
> Use NumPy's `ndindex` in `labeled_comprehension`

- dask_image/ndmeasure/__init__.py
In `labeled_comprehension`, instead of using `empty` and assigning `default_1d` the `default` value, simply use `numpy.full` to construct the `default_1d` array with the `default` value.
> Use `full` to construct 1-D NumPy array

- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils.py
- tests/test_dask_image/test_ndmeasure/test__utils.py
Instead of constructing an array of masks of where each label can be found, simply construct each label mask independently right before it is used. This way the computation of the user defined function in `labeled_comprehension` can easily happen independently for each label. Dask can usually optimize a graph like this a bit better than the former construction. Performance seems to improve here as well. Drops some code that is made unnecessary as a consequence.
> Construct separate label masks in `labeled_comprehension`

- docs/installation.rst
Update installation instructions so conda is the preferred method instead of pip.
> Update installation instructions so conda is the preferred method

- .appveyor_support/environments/tst_py37.yml
- .circleci/environments/tst_py37.yml
- .travis_support/environments/tst_py37.yml
Align the order of Python 3.7 requirements to the order used in the other environment files to make it easier to identify differences between the Python versions.
> Sort Python 3.7 requirements

- .appveyor_support/environments/tst_py27.yml
- .appveyor_support/environments/tst_py35.yml
- .appveyor_support/environments/tst_py36.yml
- .appveyor_support/environments/tst_py37.yml
- .circleci/environments/tst_py27.yml
- .circleci/environments/tst_py35.yml
- .circleci/environments/tst_py36.yml
- .circleci/environments/tst_py37.yml
- .travis_support/environments/tst_py27.yml
- .travis_support/environments/tst_py35.yml
- .travis_support/environments/tst_py36.yml
- .travis_support/environments/tst_py37.yml
To standardize the environment files a bit, make sure that everything uses `==`s when pinning exact package versions.
> Use double equals for exact package versions

- dask_image/ndmeasure/_utils.py
Newer versions of Dask have renamed `atop` to `blockwise`. Handle this by trying to import `blockwise` and falling back to `atop` if `blockwise` cannot be found.
> Handle Dask's renaming of `atop` to `blockwise`

- dask_image/ndmeasure/__init__.py
This optimize out the first call to `where` in `label` as that case should be a no-op as it merely adds `0` to the first block's label image.
---
Before you submit a pull request, check that it meets these guidelines:
1. The pull request should include tests.
2. If the pull request adds functionality, the docs should be updated. Put
your new functionality into a function with a docstring, and add the
feature to the list in README.rst.
3. The pull request should work for Python 2.7, 3.5, 3.6, and 3.7. Check
https://travis-ci.org/dask/dask-image/pull_requests
and make sure that the tests pass for all supported Python versions.
> Optimize out first `where` in `label`

- docs/index.rst
- docs/quickstart.rst
Added:
* Brief text for quickstart.rst in the dask-image docs
* Links to the dask-examples repository (specifically of interest is dask-image-quickstart,ipynb)
Is this the right way to update the docs? I checked the restructured text formatting with http://rst.ninjs.org but should I be trying to run sphinx to check left hand sidebar updates to have a 'quickstart' tab too?
> Add dask-image quickstart documentation

- docs/quickstart.rst
Our docs should also reflect the recent name change to the image processing notebook in dask-examples (https://github.com/dask/dask-examples/pull/66)
> Update quickstart.rst to match name image-processing,ipynb

- dask_image/ndfilters/_utils.py
- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils/__init__.py
- tests/test_dask_image/test_ndmeasure/test_core.py
Rename `labels` argument to `label_image` to be more descriptive.
Modify `get_docstring` to modify docstrings based on the change above.
> Rename labels in ndmeasure function arguments

- .appveyor_support/environments/tst_py37.yml
- .circleci/environments/tst_py37.yml
- .travis_support/environments/tst_py37.yml
- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils/__init__.py
- tests/test_dask_image/test_ndmeasure/test_core.py
Before you submit a pull request, check that it meets these guidelines:
1. The pull request should include tests.
2. If the pull request adds functionality, the docs should be updated. Put
your new functionality into a function with a docstring, and add the
feature to the list in README.rst.
3. The pull request should work for Python 3.5, 3.6, and 3.7. Check
https://travis-ci.org/dask/dask-image/pull_requests
and make sure that the tests pass for all supported Python versions.
> Add simple test for center_of_mass

- HISTORY.rst
I think it's an inevitable law of the universe that you only notice typos *after* you merge pull requests! This fixes the formatting of some bullet point lists in HISTORY.rst
> Fix formatting of HISTORY.rst

- setup.py
- tests/test_dask_image/test_imread/test_core.py
As scikit-image has dropped their vendored copy of tifffile ( https://github.com/scikit-image/scikit-image/pull/4235 ), switch to using tifffile directly for testing our ability to read TIFFs.
> Use tifffile for testing instead of scikit-image

- dask_image/dispatch/_dispatch_ndfilters.py
- tests/test_dask_image/test_ndfilters/test_cupy_threshold.py
Adds the fix suggested in https://github.com/cupy/cupy/issues/3909
> Add GPU support for local_threshold with method='mean'

- tests/test_dask_image/test_imread/test_core.py
Closes https://github.com/dask/dask-image/issues/160
Related work: https://github.com/dask/dask-image/pull/162
It seems there was a change introduced between tifffile version 2020.8.25 and 2020.9.3 that led to some failing tests for dask-image imread. We pin almost everything in our test environments, but we don't seem to have pinned tifffile. 
Here's the difference between those two versions of tifffile (there is a breaking change in there): https://github.com/cgohlke/tifffile/compare/v2020.8.25...v2020.9.3 Specifically, there was a change to the default argument of the `contiguous` keyword argument when saving data with tifffile.
We can explicitly specify `contiguous=True` when we write our tifffile example data for the tests. That fixes the problem, no matter what version of tifffile …
> Fix imread tests (add `contiguous=True` when saving test data with tifffile)

- dask_image/imread/__init__.py
This PR addresses performance improvements for array creation discussed in https://github.com/dask/dask-image/issues/161 and leads to arrays with smaller dask graphs (see https://github.com/dask/dask/issues/5913).
> Imread: use `da.map_blocks` instead of `da.concatenate`

- environment_doc.yml
ReadTheDocs builds recently started failing. This seems to be due to a `pip` option being passed that the version of `pip` we use here doesn't understand. In an attempt to fix this issue, try modernizing our dependencies here.
https://readthedocs.org/projects/dask-image/builds/12159489/
> Update dependencies in RTD environment

- docs/quickstart.rst
This is a sprint contribution in ScipyJapan2020 (#163).
I added a page to the docs with links to youtube talks and slides from previous presentations.
Thank you for reading.
> DOCUMENTATION: Add section Talks and Slides #163

- tests/test_dask_image/test_ndmeasure/test_core.py
FIX `LooseVersion` of #172.
This is a sprint contribution in ScipyJapan2020 (#163) .
As you can see here. `sum_labels` will added in scipy 1.6.0.
Sorry for mistake.
https://github.com/scipy/scipy/pull/12242
> FIX scipy LooseVersion for sum_labels check

- dask_image/dispatch/_dispatch_ndinterp.py
- dask_image/ndinterp/__init__.py
- docs/coverage.rst
- setup.py
- tests/test_dask_image/test_ndinterp/test_affine_transformation.py
This PR aims to add `dask-image` support for `scipy.ndimage.affine_transform` (https://github.com/dask/dask-image/issues/24).
Code changes:
- added new directory for ndinterp
- included `affine_transform` implementation in `__init__.py`
- added test that compares output to scipy for some test cases
Differences to `ndimage.affine_transformation`:
- currently, prefiltering is not supported (changing the output in case of interpolation `order > 1`)
- default order is 1
- currently, matrix is expected to have shape (ndim,) or (ndim, ndim) (because offset needs to be set for each chunk)
- modes 'reflect', 'mirror' and 'wrap' may yield different results
This implementation includes suggestions by @grlee77 about how to provide the correct spline order footprint.
Also, as @grlee77 pointed out, …
> Added dask implementation of ndimage.affine_transform in new ndinterp directory.

- dask_image/imread/__init__.py
As reported by https://github.com/dask/dask-image/issues/181 the performance of `dask_image.imread` is bad in the case of reading from many input files. Also related are https://github.com/dask/dask-image/issues/121 https://github.com/dask/dask-image/issues/161.
One problem with the current implementation that I noticed is that when calling `dask_image.imread.imread` with a file pattern such as `im_*.tif`, for each tile that is loaded `pims.open` is called on the entire file pattern. This then leads to many unnecessary instantiations of `pims.ImageSequenceND`s producing a large overhead.
In this proposed fix I use glob to match filenames and frames to call `pims.open` only on the files that are actually being loaded.
> Imread performance: reduced overhead of pim.open calls when reading from image sequence

- dask_image/dispatch/_dispatch_ndmorph.py
- dask_image/ndmorph/__init__.py
- dask_image/ndmorph/_utils.py
- tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py
Pending https://github.com/cupy/cupy/pull/3907/
This branch contains support for GPU array computation with cupy, for the dask-image ndmorph subpackage.
Related pull requests: https://github.com/dask/dask-image/pull/150, https://github.com/dask/dask-image/pull/151
Related issue: https://github.com/dask/dask-image/issues/133
> GPU support for ndmorph, binary morphological functions

- dask_image/ndfilters/_gaussian.py
Closes https://github.com/dask/dask-image/issues/192
Before you submit a pull request, check that it meets these guidelines:
1. The pull request should include tests.
2. If the pull request adds functionality, the docs should be updated. Put
your new functionality into a function with a docstring, and add the
feature to the list in README.rst.
3. The pull request should work for Python 3.6, 3.7, and 3.8. Check
https://travis-ci.org/dask/dask-image/pull_requests
and make sure that the tests pass for all supported Python versions.
> Add alias to gaussian_filter

- dask_image/ndmorph/__init__.py
- tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py
This PR fixes a small bug where we weren't setting the dask array `_meta` attribute correctly.
Here are the cupy local test results (python 3.8, cupy 9.0.0b3, dask-image main)
```
(dask-image-dev) genevieve@genevieve-G5-5500:~/GitHub/dask-image$ conda list | grep cupy
cupy                      9.0.0b3          py38hecb4491_0    conda-forge/label/cupy_rc
(dask-image-dev) genevieve@genevieve-G5-5500:~/GitHub/dask-image$ pytest -v tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py 
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.8.8, pytest-5.3.1, py-1.10.0, pluggy-0.13.1 -- /home/genevieve/anaconda3/envs/dask-image-dev/bin/python …
```
> Fix _meta type and dtype for ndmorph functions

- dask_image/ndmorph/__init__.py
- dask_image/ndmorph/_ops.py
Marvin has pointed out a much [simpler solution here](https://github.com/dask/dask-image/pull/206#issuecomment-823902083) for https://github.com/dask/dask-image/pull/206
This is probably what I should have done in the first place.
> Simplify setting meta attribute for ndmorph functions

- dask_image/ndinterp/__init__.py
- tests/test_dask_image/test_ndinterp/test_affine_transformation.py
As reported by @martinschorb in https://github.com/dask/dask-image/issues/204, there are some inconsistencies in `dask_image.ndinterp.affine_transform` with respect to the `ndimage` implementation.
This PR
1) fixes the behaviour when not providing an offset argument and adds a test for this.
2) adapts the function API to expect tuples of ints for the shape related parameters, just as the downstream `scipy` implementation does. As @martinschorb points out, the `scipy` implementation also works when providing `output_shape` as a `ndarray`, so I now explicitly perform a conversion into tuple within the function to also allow for this (please object if this doesn't make sense).
I don't see reasons for why the inconsistencies had been there in the first place and assume I had simply not been …
> affine_transform: Remove inconsistencies with ndimage implementation.

- dask_image/ndmeasure/__init__.py
This PR just adds a missing import of the `warnings` module.
If the user tries to call `dask_image.ndmeasure.sum`, it currently results in a `NameError` being raised rather than the desired warning to use `sum_labels` instead.
> BUG: add missing import of warnings in dask_image.ndmeasure

- dask_image/ndmorph/__init__.py
- tests/test_dask_image/test_ndmorph/test_ndmorph.py
This PR just adds all currently missing keyword arguments from the SciPy API for `binary_opening` and `binary_closing`. Fortunately, these same arguments were already present (and tested) for the underlying erosion and dilation functions, so this ended up being easy!
> ENH: add remaining kwargs to binary_closing and binary_opening

- dask_image/ndinterp/__init__.py
- tests/test_dask_image/test_ndinterp/test_affine_transformation.py
This PR fixes a problem revealed by the tests of @martinschorb when using `affine_transform` within `rotate` in this PR https://github.com/dask/dask-image/pull/213.
Some choices of transformation parameters, which hadn't been covered in the tests so far, require a larger input array slice to compute the output chunks.
Only code change in this PR: `+2` instead of `+1`:
```python
rel_image_slice = tuple([slice(int(rel_image_i[dim]),
int(rel_image_f[dim]) + 2)
for dim in range(n)])
```
I modified the tests to reflect the requirement for these larger input slices.
> affine_transform: increased shape of required input array slices

- dask_image/ndfourier/__init__.py
- dask_image/ndfourier/_utils.py
- tests/test_dask_image/test_ndfourier/test_core.py
The first commit here support n > 0, which is intended for use when the image to be filtered was created via a real-to-complex FFT. It is mainly just needing to use `dask.array.fft.rfftfreq` instead of `dask.array.fft.fftfreq` on the corresponding axis.
The second commit here refactors the separable filtering to avoid dense frequency arrays of shape `(image.ndim,) + image.shape`. This is done using meshgrid's `sparse=True` option to get a series of separable 1D frequency arrays instead. These can then be applied separably along each axis of the `image`, avoiding the need for `tensordot`. This should reduce computation time and peak memory usage.
I did some local benchmarking and typically saw factor 1.5-3.5 improvement in various cases. This makes sense, as rather than computing, for …
> ndfourier: support n > 0 (for rfft) and improve performance

- dask_image/dispatch/_dispatch_ndinterp.py
- dask_image/ndfilters/_utils.py
- dask_image/ndinterp/__init__.py
- docs/coverage.rst
- tests/test_dask_image/test_ndinterp/test_affine_transformation.py
- tests/test_dask_image/test_ndinterp/test_spline_filter.py
This PR adds the spline prefiltering functions that are correspond to:
`scipy.ndimage.spline_filter`
`scipy.ndimage.spline_filter1d`
The periodic modes `"wrap"` and `"grid-wrap"` are not currently supported, but all other modes are.
The one empirical nature of this implementation is the equation I came up with for estimating the overlap (depth) needed based on the interpolation order. In practice these are infinite impulse response (IIR) filters, but in practice the error terms decay pretty quickly with distance from an edge and the rate of decay is related to the magnitude of the filter poles. The current settings are enough for tests to pass at the tolerance of 1e-6 used in the tests. With the current default, the `depth` currently ends up being 11, 14, 19 and 22 for spline `order` of …
> Add spline_filter and spline_filter1d

- docs/release/release_guide.rst
Closes https://github.com/dask/dask-image/issues/214
Also see https://github.com/dask/community/issues/100
> Switch to CalVer (calendar versioning)

- docs/release/release_guide.rst
Dask calendar versioning uses the format `YYYY.MM.DD` (and not `YY.MM.DD`)
> Update release guide, Dask CalVer uses YYYY.MM.DD

- dask_image/ndmeasure/_utils/__init__.py
The small update in this PR means our tests will pass with both old and newer dask versions.
The version of dask we have pinned in the test environments is quite old (as in, before the calver standard was adopted for dask releases). I want to depend on a more up-to-date version of dask (eg: for https://github.com/dask/dask-image/pull/240).
> Upgrade for compatibility with latest dask release

- dask_image/ndfilters/_conv.py
- tests/test_dask_image/test_ndfilters/test__conv.py
Closes [#242]
This bugged was caused by letting Scipy handle the boundary conditions which cannot work when `mode = "wrap"` and the array has more than one chunk. 
Quick explanation of what happened : 
The old function does 
```python
result = image.map_overlap(
dispatch_convolve(image),
depth=depth,
boundary=boundary,
dtype=image.dtype,
meta=image._meta,
weights=weights,
mode=mode,
cval=cval,
origin=origin,
)
```
This means that we will apply `scipy.ndimage.convolve` to each chunk. When `mode == "wrap"`, the wrapping will be done on the chunks which means that the values used for the boundaries are the edge values of the chunk and not the array, hence why it doesn't work properly. This is the only mode for which it happens because wrapping is the only case where being limited to a chunk …
> Fix wrap bug in ndfilters convolve and correlate

- continuous_integration/gpuci/axis.yaml
- continuous_integration/gpuci/build.sh
This PR adds the required build files to run gpuCI on all PRs opened in this repo; based on these files, the `cupy` marked tests in this repo would be run in an environment with:
- ubuntu 18.04
- python 3.8
- cudatoolkit 11.2
- the latest pre-release of cupy
- (note that since tests here do not depend on a RAPIDS release, `RAPIDS_VER` has no impact on the environment)
Some additional things that should be done:
Note that gpuCI is not currently enabled on this repo - ideally, that would be done after merging these files in. To see an example of the gpuCI checks running, view https://github.com/charlesbluca/dask-image/pull/1.
cc @jakirkham @GenevieveBuckley
> Set up gpuCI testing on PRs

- continuous_integration/gpuci/axis.yaml
- continuous_integration/gpuci/build.sh
Makes some updates to the gpuCI matrix which should be passing once it is enabled on this repo:
- Removes `RAPIDS_VER` from the build matrix, as no RAPIDS projects are required for the cupy tests
- Bumps `CUDA_VER` to 11.5; as of https://github.com/rapidsai/dask-build-environment/pull/24 we are now only building Dask gpuCI images using CUDA 11.5 to match up with the gpuCI testing ran on RAPIDS projects
> Remove `RAPIDS_VER` axis, bump `CUDA_VER` in gpuCI matrix

- setup.py
The minimum supported python version tested with CI is python 3.6. 
That's been the case for a while, I just missed this one spot when we bumped the versions in https://github.com/dask/dask-image/pull/131
> Update min python version in setup.py

- docs/coverage.rst
Because of course I noticed this update was missing from the docs as soon as I merged https://github.com/dask/dask-image/pull/240
> Docs: Add `find_objects` to the coverage table

- HISTORY.rst
This PR adds the release notes for version 2021.12.0
> Release notes for version 2021.12.0

- dask_image/dispatch/_dispatch_ndfilters.py
- dask_image/ndfilters/_conv.py
- dask_image/ndfilters/_diff.py
- dask_image/ndfilters/_edge.py
- dask_image/ndfilters/_gaussian.py
- dask_image/ndfilters/_generic.py
- dask_image/ndfilters/_order.py
- dask_image/ndfilters/_smooth.py
- environment_doc.yml
- tests/test_dask_image/test_ndfilters/test__conv.py
- tests/test_dask_image/test_ndfilters/test__diff.py
- tests/test_dask_image/test_ndfilters/test__edge.py
- tests/test_dask_image/test_ndfilters/test__gaussian.py
- tests/test_dask_image/test_ndfilters/test__generic.py
- tests/test_dask_image/test_ndfilters/test__order.py
- tests/test_dask_image/test_ndfilters/test__smooth.py
Fix #260 
Import from `scipy.ndimage` rather than `scipy.ndimage.filters` as the filters namespace is now deprecated.
> Avoid DeprecationWarnings when importing scipy.ndimage filter functions

- docs/conf.py
- environment_doc.yml
On Monday, June 6th, dask.org will go live with a new design (see https://github.com/dask/community/issues/220). This PR is in preparation for the theme update for `dask-sphinx-theme` and can be merged in *after* https://github.com/dask/dask-sphinx-theme/pull/67 on Monday.
cc @jacobtomlinson @jsignell
> Update docs theme for rebranding

- dask_image/imread/__init__.py
- tests/test_dask_image/test_imread/test_core.py
`dask_image.imread.imread` can include glob strings in the filename argument.
Currently, the results of the glob operation are sorted using `sorted`, a behviour that is not described in the doctring.
`sorted` sorts alphabetically which causes files such as `10.tif`, `9.tif` to be read in this order, which is counter-intuitive.
A common strategy adopted by users to circumenvent such file name problems is to zero-pad all numbers in a string. 
This PR adds a `sortfunc` argument to to `imread`, which allows to pass in a custom sort function. A use case for this  is to pass in a function that performs natural sort, which will sort strings of numbers numerically. Such a use-case is shown in the included test.
The docstring for imread has been updated to include the new argument, which also …
> Use natural sorting in  `imread(...)` when globbing multiple files 

- .github/workflows/test.yml
- continuous_integration/environment-3.7.yml
- continuous_integration/environment-3.8.yml
- continuous_integration/environment-3.9.yml
Previously Coveralls was setup with CI to receive coverage data and report any lines missed by testing. However this fell out of use due to a few migrations of CI in the interim, which often lacked support for Coveralls. Fortunately there is GitHub Actions support of Coveralls. So this sets up Coveralls support with GitHub Actions (along with any other refreshing needed).
> Setup Coveralls with GitHub Actions

- continuous_integration/environment-doc.yml
Closes issue https://github.com/dask/dask-image/issues/277
> Pin to jinja2<3.1 to avoid Readthedocs build error

- dask_image/ndmeasure/_utils/__init__.py
- setup.py
Fixes https://github.com/dask/dask-image/issues/232
Bumps the Dask minimum version to 1.1.0, which in turn allows some special casing logic to be dropped.
> Require Dask 1.1.0+

- dask_image/ndfilters/__init__.py
- tests/test_dask_image/test_ndfilters/test__gaussian.py
- tests/test_dask_image/test_ndfilters/test_cupy_ndfilters.py
Test the `gaussian` alias to ensure it is counted in test coverage.
> Test `gaussian` alias

- continuous_integration/environment-3.11.yml
- continuous_integration/environment-3.8.yml
- continuous_integration/environment-doc.yml
- setup.py
Closes https://github.com/dask/dask-image/issues/258
Dependabot suggests bumping the minimum allowable version of dask to v2021.10.0, as a security update.
> An issue was discovered in Dask (aka python-dask) through 2021.09.1. Single machine Dask clusters started with dask.distributed.LocalCluster or dask.distributed.Client (which defaults to using LocalCluster) would mistakenly configure their respective Dask workers to listen on external interfaces (typically with a randomly selected high port) rather than only on localhost. A Dask cluster created using this method (when running on a machine that has an applicable port exposed) could be used by a sophisticated attacker to achieve remote code execution.
Once this is done, we should probably also publish another release to PyPI (which …
> Security update: Dask v2021.10.0 as minimum allowable version

- dask_image/ndfilters/_threshold.py
- tests/test_dask_image/test_ndfilters/test_cupy_threshold.py
Closes https://github.com/dask/dask-image/issues/256
This PR:
1. Removes some unnecessary tests. I wrote the tests several years ago, and I don't think there was a good reason to have them in there. It looks like I just wanted to have higher test code coverage at the time
2. It also explicitly specifies the `like=` kwarg when computing `sigma` from `block_size` for the gaussian local threshold function. I've found an edge case where `da.asarray(cupy_array)` correctly creates a dask array with cupy chunks, but `da.asarray(cupy.nan)` doesn't make a cupy-backed dask array (because `type(cupy.nan)` returns float). To avoid this problem, we use the `like=` kwarg to match the array type to the input image type.
> Update NaN block size tests for threshold_local function

- dask_image/imread/__init__.py
- dask_image/imread/_utils.py
This PR groups all imread functions into the same file.
I find it annoying to have all the imread functions together, *except* for one little two line function which is split onto another page. It also makes it weirdly difficult to fully understand what is happening with the code, so I'm changing it.
> Group all imread functions together in the same file

- tests/test_dask_image/test_ndmeasure/test_find_objects.py
Increase test coverage of `find_objects` by testing this error case
https://github.com/dask/dask-image/blob/d25a1298636fec9f94840037ee6c0043a13ecb05/dask_image/ndmeasure/__init__.py#L229-L230
> Test `find_objects` w/incorrect array type

- setup.py
I just realised that although `tifffile` is imported in `dask_image.imread.__init__`, it's only part of the test requirements. Indeed, this leads to an import error in a fresh environment.
This PR upgrades `tifffile >=2018.10.18` from a test requirement to a regular requirement in `setup.py`. Regarding the version, `2018.10.18`, which had been pinned as a test requirement, also provides `natural_sorted` as introduced in https://github.com/dask/dask-image/pull/265.
> Make tifffile regular requirement

- CONTRIBUTING.rst
Closes https://github.com/dask/dask-image/issues/266
This PR adds information about the GPU continuous integration to the contributing docs.
> Add GPU CI info to contributing docs

- docs/release/generate_release_notes.py
The release notes script generated produced an error, so this small update makes it work again for newer versions of `pygithub`.
Honestly most of this functionality is now included as part of the Github release page (https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) so we could potentially get rid of the script altogether.
> Update release notes script

- docs/coverage.rst
Closes https://github.com/dask/dask-image/issues/197
This PR adds information about whether functions have GPU support (i.e. can use [dask arrays backed](https://docs.dask.org/en/stable/gpu.html#arrays) with [cupy](https://cupy.dev/) chunks as input to the function)
- File: https://github.com/dask/dask-image/blob/main/docs/coverage.rst
- Webpage: https://image.dask.org/en/latest/coverage.html
> Docs: add GPU support info to coverage table

- setup.py
This aligns with Dask 2021.10.0's own NumPy requirement.
https://github.com/dask/dask/blob/2021.10.0/setup.py#L13
> Require NumPy 1.18+

- continuous_integration/environment-3.10.yml
- continuous_integration/gpuci/build.sh
Attempt to update the conda environment in the GPU CI images before running tests, which should hopefully allow us to capture environment changes like those made in #315 without needing to rebuild images.
> Update GPU conda environment before running tests

- README.rst
I noticed that the CI badge is saying failing, but the CI isn't failing - looks like it just needed updating to the current workflow name. See https://github.com/dstansby/dask-image/blob/patch-1/README.rst for the correctly rendered badge on this branch.
> Fix GitHub actions README badge

- dask_image/ndmeasure/_utils/_label.py
- tests/test_dask_image/test_ndmeasure/test_core.py
In https://github.com/dask/dask-image/issues/320 @vecxoz showed that the current implementation of `dask_image.ndmeasure.label` is not equivalent to `scipy.ndimage.label` when using a full structuring element. This PR fixes this.
Explanation:
`dask_image.ndmeasure.label` computes label maps for each block independently and then merges these by joining labels that are connected across block boundaries. However, it currently only considers orthogonal boundaries between chunks, which can lead to problems at diagonal chunk borders when using diagonal connectivity structuring elements.
Code changes:
In terms of implementation, `dask_image.ndmeasure.label` considers chunk boundaries by obtaining two-pixel wide slices that connect pairs of neighboring chunks using the function …
> ndmeasure.label: fix for arbitrary struct elements

- dask_image/dispatch/_dispatch_ndfilters.py
- tests/test_dask_image/test_imread/test_cupy_imread.py
- tests/test_dask_image/test_ndfilters/test_cupy_ndfilters.py
- tests/test_dask_image/test_ndfilters/test_cupy_threshold.py
- tests/test_dask_image/test_ndfourier/test_core.py
- tests/test_dask_image/test_ndinterp/test_affine_transformation.py
- tests/test_dask_image/test_ndinterp/test_spline_filter.py
- tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py
This PR moves functions from the `cupyx.scipy.ndimage.filters` namespace to `cupyx.scipy.ndimage`, fixing https://github.com/dask/dask-image/issues/324.
Secondly it changes a reference to `scipy.ndimage.fourier` into `scipy.ndimage` in test functions, anticipating the [removal](https://github.com/scipy/scipy/blob/2ff5a46ec3ecc86427e73801b7c6151ed29b6dea/scipy/ndimage/fourier.py#L1C1-L3C18) of `scipy.ndimage.fourier` in scipy version 2.
> Moved functions from ndimage submodules to ndimage namespace

- dask_image/ndfilters/_threshold.py
- tests/test_dask_image/test_ndfilters/test_cupy_threshold.py
This PR fixes https://github.com/dask/dask-image/issues/327 by
- adding the cupy mark to the ignored test
- passing `sigma` in `threshold_local` (gaussian mode) as a numpy array instead of as an array of the same type as the input image.
> Added missing cupy test mark and fixed cupy threshold

- HISTORY.rst
Added curated release notes and recommendation to use cupy >= 9.0.0 to `HISTORY.rst`.
> Added 2023.08.0 release notes

- HISTORY.rst
After creating release candidate 2023.08.0, github actions showed the following error when trying to upload to pypi:
Using `twine check dist/*` locally, I found the error was caused by the newly added title underline in HISTORY.rst being too short:
```rst
2023.08.0 (2023-08-03)
------------------
```
At first I was bit puzzled because I had copied this directly from the output of `generate_release_notes.py`, however previous release summaries in `HISTORY.rst` contained long enough title underlines.
Maybe it'd be a good addition to `generate_release_notes.py` to automatically adapt the title underline to the title determined by the version. Also, it could make sense to include the suggestion to `twine check dist/*` in the release guide.
Something else to mention here is that twine warns …
> Extended title underline in HISTORY.rst to fix twine error

- setup.py
Follow up to PR ( https://github.com/dask/dask-image/pull/315 )
This is needed for `sdist`s & `whl`s to restrict Python version.
> Use `>=3.9` in `python_requires` in `setup.py`

- docs/release/generate_release_notes.py
- docs/release/release_guide.rst
While creating the 2023.08.0 release (https://github.com/dask/dask-image/issues/330) I could test the fantastic release guide by @GenevieveBuckley and found it super useful. Basically everything worked as described (there was some trouble during the release but unrelated to the release notes).
I didn't find that any particular step could be much simpler, but I completely agree that there's potential for automatization as discussed in https://github.com/dask/dask-image/issues/331.
One little problem that I encountered was that after copying the release notes generated by `generate_release_notes.py` to `HISTORY.rst` and creating a release (candidate), twine complained about invalid restructured text. It turned out to be a too short title underline …
> Additions to release guide and change to release note generation script

- continuous_integration/environment-doc.yml
This PR addresses https://github.com/dask/dask-image/issues/351 by implementing https://github.com/dask/dask-sphinx-theme/issues/68#issuecomment-1893198477.
Further discussions here https://github.com/readthedocs/readthedocs.org/issues/11140.
> Workaround for the sphinx version problem in the readthedocs build environment

- setup.py
Fixes https://github.com/dask/dask-image/issues/362, see https://github.com/dask/dask/pull/11035.
> Pin dask to 2024.4.1 to avoid error during dask.dataframe import with python 3.11.9

- .github/workflows/test_and_deploy.yml
- continuous_integration/environment-3.10.yml
- continuous_integration/environment-3.11.yml
- continuous_integration/environment-3.9.yml
- continuous_integration/environment-doc.yml
This PR:
* Updates the python 3.9 CI test environment, with a configuration I've checked works on arm64 Mac.
* Updates all of the environment yaml files to use dask==2024.4.1 (see https://github.com/dask/dask-image/pull/363)
I didn't think we needed to do this, since all of the CI checks for https://github.com/dask/dask-image/pull/363 passed before we merged it, but manually triggering CI on the main branch is failing ([see here](https://github.com/dask/dask-image/actions/runs/9074896375)). So this is an attempt to fix that problem.
> Update CI test environments

- tests/test_dask_image/test_ndfilters/test__threshold.py
- tests/test_dask_image/test_ndfilters/test_cupy_threshold.py
Followup to PR https://github.com/dask/dask-image/pull/366 (I forgot to make equivalent changes for the cupy tests).
> Fix cupy pytest errors

- HISTORY.rst
- docs/release/release_guide.rst
Release notes for v2024.05.0
Xref: https://github.com/dask/dask-image/issues/352
> Release notes for v2024.05.0

- pyproject.toml
It looks like a few dependencies had higher minimum versions when using `setup.py`
https://github.com/dask/dask-image/blob/243fb0a5de55f5bc5b8650985d26381a7c22889e/setup.py#L31-L39
Though we wound up with older versions after switching to `pyproject.toml`
https://github.com/dask/dask-image/blob/49d9c336bc4551bbfc89c7d3527b0c176ae6f4a5/pyproject.toml#L26-L35
Guessing this is just because the `pyproject.toml` PR has fallen out of date in this area and we missed it
So went ahead and bumped these. Though please let me know if I'm missing something
> Update minimum versions in `dependencies`

- .readthedocs.yml
- pyproject.toml
* Install on RTD with `pip` (keeps the git repo clean, which likely causes the ".dev0" version issue)
* Disable `setuptools-scm`'s `version_scheme` guess (states versions in terms of distance passed the old version)
> Install dask-image with `pip` on RTD

- .readthedocs.yml
Based on [this recommendation from RTD]( https://docs.readthedocs.io/en/stable/build-customization.html#avoid-having-a-dirty-git-index ), ask `git` to ignore some changes RTD makes. Hopefully should fix `setuptools-scm` issues we have seen ( https://github.com/dask/dask-image/issues/375 )
> Have `git` ignore some RTD changes

- docs/conf.py
Closes https://github.com/dask/dask-image/issues/375
Fix problem where RTD displays full release version string (eg: X.Y.Z.dev0+gXXXXXX)., not shorter X.Y.Z version
> ReadTheDocs: fix displayed version number in top left corner

- docs/conf.py
Closes https://github.com/dask/dask-image/issues/382
ReadTheDocs is deprecating sphinx context injection. We need to set the canonical url a different way.
> Update conf.py, sphinx context injection deprecated in ReadTheDocs

- .github/workflows/test_and_deploy.yml
- dask_image/ndinterp/__init__.py
- dask_image/ndmeasure/__init__.py
- dask_image/ndmeasure/_utils/_find_objects.py
- tests/test_dask_image/test_imread/test_core.py
With this PR I started out just wanting to ensure compatibility with numpy 2 as reported in https://github.com/dask/dask-image/issues/392, however different issues came up in the tests (and if unaddressed they make the CI fail), so I decided to address them together in the same PR.
Summary:
1) Use `np.ptp` instead of the method to ensure compatibility with numpy 2 as reported in https://github.com/dask/dask-image/issues/392.
2) Replace the deprecated `tifffile.TiffWriter.save` by `tifffile.TiffWriter.save`, see [here](https://github.com/cgohlke/tifffile/blame/f1d053c1f9922a207b84df615eefa52c6fbae3bb/tifffile/tifffile.py#L122C7-L122C7).
3) `dask-image` currently doesn't pass tests with `dask>=2025.1.0` because of https://github.com/dask/dask-image/issues/335 which came back because of …
> Fix CI test failures

- tests/test_dask_image/test_imread/test_cupy_imread.py
Fixes https://github.com/dask/dask-image/issues/397
Recently [`tifffile` removed the `save` method]( https://github.com/cgohlke/tifffile/blob/78b57cf84bd92528ba8877ea4972769bb4d43600/tifffile/tifffile.py#L132 ), which has been deprecated. Switch to the `write` method to fix it.
> Use `tifffile.TiffWriter`'s `write` method in `test_cupy_imread`
